services:
  agent-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${AGENT_DB_PASSWORD:-ctrl_agent}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_agent}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_AGENT_POSTGRES_PORT:-5432}:6432"

  mcp-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${MCP_DB_PASSWORD:-ctrl_mcp}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_mcp}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_MCP_POSTGRES_PORT:-5432}:5432"

  tenant-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:  
      POSTGRES_PASSWORD: ${TENANT_DB_PASSWORD:-ctrl_tenant}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_tenant}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_TENANT_POSTGRES_PORT:-5432}:5432"

  user-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${USER_DB_PASSWORD:-ctrl_user}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_user}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_USER_POSTGRES_PORT:-5432}:5432"

  admin-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${ADMIN_DB_PASSWORD:-ctrl_admin}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_admin}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_ADMIN_POSTGRES_PORT:-5432}:5432"

  model-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${MODEL_DB_PASSWORD:-ctrl_model}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_model}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_MODEL_POSTGRES_PORT:-5432}:5432"

  gateway-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${GATEWAY_DB_PASSWORD:-ctrl_gateway}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_gateway}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_GATEWAY_POSTGRES_PORT:-5432}:5432"

  integration-db:
    image: postgres:15-alpine
    restart: always
    env_file:
      - ./middleware.env
    environment:
      POSTGRES_PASSWORD: ${INTEGRATION_DB_PASSWORD:-ctrl_integration}
      POSTGRES_DB: ${POSTGRES_DB:-ctrl_integration}
      PGDATA: ${PGDATA:-/var/lib/postgresql/data/pgdata}
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "${EXPOSE_INTEGRATION_POSTGRES_PORT:-5432}:5432"

  redis:
    image: redis:6-alpine
    restart: always
    volumes:
      - ./volumes/redis/data:/data
    command: redis-server --requirepass ${REDIS_PASSWORD:-ctrl_password}
    ports:
      - "${EXPOSE_REDIS_PORT:-6379}:6379"

  consul:
    image: consul:1.15.3
    restart: always
    ports:
      - "${EXPOSE_CONSUL_PORT:-8500}:8500"

